<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKJRKmgc\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKJRKmgc/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerKJRKmgc.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerKJRKmgc\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerKJRKmgc\appAppKernelProdContainer([
    'container.build_hash' => 'KJRKmgc',
    'container.build_id' => 'dad639c5',
    'container.build_time' => 1683450026,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKJRKmgc');
