<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJL8uwxb\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJL8uwxb/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJL8uwxb.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJL8uwxb\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJL8uwxb\appAppKernelProdContainer([
    'container.build_hash' => 'JL8uwxb',
    'container.build_id' => '408cf235',
    'container.build_time' => 1683449991,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJL8uwxb');
